pr:
  branches:
    exclude:
      - '*'
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - /

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

variables:
- group: azureml_variables

pool:
  vmImage: 'ubuntu-latest'
# pool:
#   name: NWKAgentPool

stages:
- stage: 'Publish_AML_Pipeline'
  displayName: 'Publish AML Pipeline'
  jobs:
  - job: "AML_PIPELINE"
    container: mlops
    displayName: "Build and Publish AML Pipeline"
    timeoutInMinutes: 0
    steps:
    - task: Bash@3
      inputs:
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        targetType: inline
        script: |
          python -m pip install jupyter nbconvert
          jupyter nbconvert --to script AML_CreateTrainingPipeline.ipynb
      displayName: 'Convert Jupyter Notebook to Python Script'

    - task: AzureCLI@1
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          # Invoke the Python building and publishing a training pipeline
          python -m pip install pip --upgrade
          python -m pip install azureml-defaults azureml-pipeline-core azureml-pipeline-steps
          python -m AML_CreateTrainingPipeline
      displayName: 'Publish AML Training Pipeline'